name: MBsociety
main: MBsociety\Main
version: 1.2.1
api: 
- 3.0.0
- 4.0.0
load: POSTWORLD
author: MengBao
depend: 
- EconomyAPI
commands:
 公会 :
  description: 公会主命令
  permission: plugin.a
  usage: '/公会'
 结婚 :
  description: 结婚主命令
  permission: plugin.a
  usage: '/结婚'
 Ushop :
  description: 商店ui唤醒命令
  permission: plugin.a
  usage: '/Ushop'
 myop :
  description: 管理op命令
  permission: plugin.b
  usage: '/myop'
 称号 :
  description: 称号主命令
  permission: plugin.a
  usage: '/称号'
 vip :
  description: vip命令
  permission: plugin.a
  usage: '/vip'
 opvip :
  description: 管理vip命令
  permission: plugin.b
 mbhelp :
  description: MBsoc帮助命令
  permission: plugin.a
  
permissions:
 plugin.a:
  default: true
  description: 普通指令
 plugin.b:
  default: op
  description: op指令
 